server:
  port: 8060
spring:
  application:
    name: auth-service
  redis:
    host: localhost
    port: 6379

## Eureka - Service Discovery ##
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8020/eureka/

# It is information that must be hidden. (But temporarily public)
jwt:
  secret: yeonjeong
