server:
  port: 8000
spring:
  application:
    name: gateway-service

## Eureka - Service Discovery ##
## Gateway is also eureka client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8020/eureka/