server:
  port: 8000
spring:
  application:
    name: gateway-service

## Eureka - Service Discovery ##
## Gateway is also eureka client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8020/eureka/

---

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**