spring:
  config:
    activate:
      on-profile: local
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create
    session:
      store-type: jdbc
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/auth_system_user?serverTimezone=UTC&characterEncoding=UTF-8
    username: auth-system
    password: qwer1234
    driverClassName: org.mariadb.jdbc.Driver