server:
  port: 8070
spring:
  application:
    name: user-service
  profiles:
    active: test

## Eureka - Service Discovery ##
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8020/eureka/